
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF

SELECT 
CASE 
WHEN S.USERNAME NOT IN ('SYS','SYSMAN','SYSTEM','DBSNMP','PUBLIC','ANTBDU','SVT','AXISATM') THEN 'ALTER SYSTEM KILL SESSION '''|| S.SID ||','|| S.SERIAL# || ''' IMMEDIATE;' 
ELSE '' END SENTENCIA
FROM V$SESSION S, V$SQL SQL, V$PROCESS P
WHERE SQL.SQL_ID(+) = S.SQL_ID
AND S.PADDR = P.ADDR(+)
AND UPPER(S.USERNAME) NOT IN ('SYS','SYSTEM','SYSMAN','DBSNMP','OUTLN','MDSYS','ORDSYS', 
'ORDPLUGINS','CTXSYS','DSSYS','PERFSTAT','WKPROXY','WKSYS', 
'WDMSYS','XDB','ANONYMOUS','ODM','ODM_MTR','OLAPSYS', 
'TRACESVR','REPADMIN','AURORA$ORB$UNAUTHENTICATED', 
'AURORA$JIS$UTILITY$','OSE$HTTP$ADMIN','BIGB')
ORDER BY S.LOGON_TIME DESC;
EXIT;

