
#EXPORT VARIABLES DE ENTORNO
#export ORACLE_UNQNAME=ATM
export ORACLE_UNQNAME=srvbdatm
#export ORACLE_SID=ATM
export ORACLE_SID=srvbdatm

#IR AL DIRECTORIO. SE ASUME QUE EL USUARIO QUE EJECUTA LA TAREA TIENE PERMISOS SOBRE EL DIRECTORIO
#cd /datos/RESPALDO/
cd /cloudfs/RESPALDO/

#MOVER DMP ACTUALES AL DIRECTORIO DE RESPALDO DIARIO 

#REALIZAR EL EXPORT DEL ESQUEMA ANTBDU. SE ASUME QUE EL DIRECTORY ESTA CREADO EN LA BD

$ORACLE_HOME/bin/expdp userid=\'/ as sysdba\' directory=DATA_PUMP DUMPFILE=EXPORT_wf_tramites_rezago_ant%U.dmp LOGFILE=EXPORT_AXISATM_wf_tramites_rezago_ant.log PARALLEL=9 TABLES=AXISATM.wf_tramites_rezago_ant

#REGRESAR AL HOME DEL USUARIO
cd $HOME


