
#EXPORT VARIABLES DE ENTORNO
#export ORACLE_UNQNAME=ATM
export ORACLE_UNQNAME=srvbdatm
#export ORACLE_SID=ATM
export ORACLE_SID=srvbdatm

#IR AL DIRECTORIO. SE ASUME QUE EL USUARIO QUE EJECUTA LA TAREA TIENE PERMISOS SOBRE EL DIRECTORIO
#cd /datos/RESPALDO/
cd /cloudfs/RESPALDO/

#MOVER DMP ACTUALES AL DIRECTORIO DE RESPALDO DIARIO 
#/bin/mv /cloudfs/RESPALDO/*.dmp /cloudfs/RESPALDO/DIARIO/

#REALIZAR EL EXPORT DEL ESQUEMA ANTBDU. SE ASUME QUE EL DIRECTORY ESTA CREADO EN LA BD
#$ORACLE_HOME/bin/expdp userid=\'/ as sysdba\' directory=RESPALDOS DUMPFILE=EXPORT_SCHEMA_ANTBDU%U.dmp LOGFILE=EXPORT_SCHEMA_ANTBDU.log PARALLEL=9 SCHEMAS=ANTBDU


$ORACLE_HOME/bin/expdp userid=\'/ as sysdba\' directory=DATA_PUMP DUMPFILE=EXPORT_DATOS_NOTIFICACIONES%U.dmp LOGFILE=EXPORT_DATOS_NOT.log PARALLEL=9 TABLES=notificaciones.datos_notificacion  

#REGRESAR AL HOME DEL USUARIO
cd $HOME


